### ISSUE TITLE
over mpz "logic_error: Floor Division inconsistent with cmp()/subtract()"

### ISSUE THREAD

**Issue by videlec** [flatsurf/intervalxt#90] opened 2020-03-04 10:12 UTC
```
from gmpxxyy import mpz
from pyintervalxt import intervalxt
permutation = [1, 0]
lengths = [2, 1]
lengths = intervalxt.sample.Lengths[mpz](lengths)
iet = intervalxt.makeIET(lengths, permutation)
iet.zorichInduction()
```
It works fine with `int` instead of `mpz`.

**Comment by saraedum** [comment] 2020-03-04 10:33
As a workaround, add this in the beginning:
```python
>>> import cppyy
>>> cppyy.include('intervalxt/sample/mpz-arithmetic.hpp')
```

**Comment by saraedum** [comment] 2020-03-04 10:36
Duplicate of #84. The underlying issue is the same.

**Closed by saraedum** 2020-03-04 10:36 UTC
Labels: bug

**Comment by videlec** [comment] 2020-03-04 10:39
Notice that 84 is a double issue as we end up with a negative length.

**Comment by saraedum** [comment] 2020-03-04 10:54
But that one is actually #85 now :)
